"""Initial audiobook e-commerce schema

Revision ID: d0a3a181d787
Revises: 
Create Date: 2025-09-21 16:21:12.289692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0a3a181d787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('sample_url', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('narrator_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiobooks_price_cents'), 'audiobooks', ['price_cents'], unique=False)
    op.create_index(op.f('ix_audiobooks_publication_date'), 'audiobooks', ['publication_date'], unique=False)
    op.create_index(op.f('ix_audiobooks_slug'), 'audiobooks', ['slug'], unique=True)
    op.create_index(op.f('ix_audiobooks_status'), 'audiobooks', ['status'], unique=False)
    op.create_index(op.f('ix_audiobooks_title'), 'audiobooks', ['title'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_clerk_user_id'), 'user_profiles', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('chapter_title', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_audiobook_id'), 'audio_files', ['audiobook_id'], unique=False)
    op.create_table('audiobook_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiobook_categories_audiobook_id'), 'audiobook_categories', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_audiobook_categories_category_id'), 'audiobook_categories', ['category_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_added_at'), 'cart_items', ['added_at'], unique=False)
    op.create_index(op.f('ix_cart_items_audiobook_id'), 'cart_items', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_cart_items_session_id'), 'cart_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_audiobook_id'), 'reviews', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('download_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_logs_audio_file_id'), 'download_logs', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_download_logs_audiobook_id'), 'download_logs', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_download_logs_created_at'), 'download_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_logs_user_id'), 'download_logs', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_audiobook_id'), 'order_items', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_service', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_status', sa.String(length=20), nullable=False),
    sa.Column('upload_progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_audio_file_id'), 'transcriptions', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_transcriptions_status'), 'transcriptions', ['status'], unique=False)
    op.create_table('user_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('audiobook_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_library_audiobook_id'), 'user_library', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_user_library_order_id'), 'user_library', ['order_id'], unique=False)
    op.create_index(op.f('ix_user_library_purchased_at'), 'user_library', ['purchased_at'], unique=False)
    op.create_index(op.f('ix_user_library_user_id'), 'user_library', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_library_user_id'), table_name='user_library')
    op.drop_index(op.f('ix_user_library_purchased_at'), table_name='user_library')
    op.drop_index(op.f('ix_user_library_order_id'), table_name='user_library')
    op.drop_index(op.f('ix_user_library_audiobook_id'), table_name='user_library')
    op.drop_table('user_library')
    op.drop_index(op.f('ix_transcriptions_status'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_audio_file_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_audiobook_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_download_logs_user_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_created_at'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_audiobook_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_audio_file_id'), table_name='download_logs')
    op.drop_table('download_logs')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_audiobook_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_session_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_audiobook_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_added_at'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_audiobook_categories_category_id'), table_name='audiobook_categories')
    op.drop_index(op.f('ix_audiobook_categories_audiobook_id'), table_name='audiobook_categories')
    op.drop_table('audiobook_categories')
    op.drop_index(op.f('ix_audio_files_audiobook_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_clerk_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audiobooks_title'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_status'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_slug'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_publication_date'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_price_cents'), table_name='audiobooks')
    op.drop_table('audiobooks')
    # ### end Alembic commands ###
